version: '2'

services:
  database:
    image: neo4j:4.4
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/77A18HL6
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  
  backend:
    build:
      context: ./docker-server
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 7687
      DATABASE_USER: neo4j
      DATABASE_PASSWORD: 77A18HL6
    depends_on:
      database: 
        condition: service_healthy
