INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(23, 'webshit', 'css sass', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(5, 'jvm', 'jvm', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(106, 'db-migrator', 'flyway liquibase', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(10, 'maven', 'maven mvn', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(76, 'hardware', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(11, 'scala', 'scala', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(25, 'graphics', 'graphics', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(8, 'rust', 'rust', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(68, 'jms', 'JMS', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(46, 'jpa', 'JPA', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(72, 'weblogic', 'Weblogic', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(9, 'wildfly', 'Wildfly', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(15, 'hibernate', 'hibernate', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(93, 'graphql', 'graphQL', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(105, 'aws', 'AWS', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(103, 'kafka', 'kafka', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(22, 'javascript', 'javascript " js"', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(84, 'angular', 'angular', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(98, 'nodejs', 'nodejs', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(92, 'typescript', 'typescript "ts "', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(16, 'linux', 'linux ubuntu', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(94, 'bundler', 'webpack rollup vite', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(40, 'clojure', 'clojure clj', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(4, 'postgres', 'postgres psql', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(3, 'java', 'java', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(26, 'machine-learning', 'keras tensorflow deeplearning4j', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(17, 'liferay-6', 'liferay', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(34, 'liferay-7', 'liferay', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(108, 'nosql', '', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(77, 'ide', 'intelliJ netbeans eclipse vscode', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(27, 'sql', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(33, 'virtualmachine', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(28, 'algorithm', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(38, 'portlet', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(31, 'frontend', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(51, 'assembly', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(57, 'program', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(44, 'security', 'security', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(32, 'backend', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(13, 'functional', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(29, 'optimization', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(47, 'orm', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(62, 'perf', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(66, 'database', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(70, 'network', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(64, 'represent', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(71, 'embedded', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(74, 'sysadmin', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(80, 'audio', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(81, 'mapping', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(14, 'beam', 'BEAM', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(21, 'arquillian', 'Arquillian', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(49, 'gradle', 'gradle', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(79, 'gui', 'gui', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(41, 'jackson', 'jackson', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(24, 'wicket', 'Wicket', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(52, 'command', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(53, 'config', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(54, 'error', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(56, 'tool', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(55, 'search', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(20, 'mq', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(58, 'webtech', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(100, 'service-descriptor', 'swagger wsdl', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(43, 'junit', 'junit', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(12, 'go-lang', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(45, 'auth', 'authentication authorization', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(102, 'source-control', 'git svn', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(99, 'serverless', 'lambda function', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(50, 'c-lang', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(48, 'util-class', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(19, 'model-checking', 'alloy tla', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(42, 'oracle-db', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(89, 'mongo', 'mongo', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(85, 'multithreading', 'thread', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(90, 'debug', 'debug', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(61, 'javaee', 'javaee jee jakartaEE', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(107, 'jargon', '', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(82, 'hack', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(36, 'testing', 'test', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(87, 'xml-tech', 'xml xsd wsdl', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(95, 'documentformat', 'latex markdown', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(88, 'react', 'react', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(35, 'ci/cd', 'github gitlab jenkins pipeline', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(83, 'vision', '"open cv"', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(60, 'logging', 'logging log4j slf4j logback', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(91, 'spring_export_2022_02', NULL, true);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(63, 'matek', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(39, 'spring', 'Spring', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(73, 'protip', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(78, 'dotnet', 'dotnet', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(30, 'android', 'android', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(6, 'docker', 'docker', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(2, 'erlang', 'erlang', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(7, 'haskell', 'haskell', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(67, 'kotlin', 'kotlin', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(59, 'kubernetes', 'Kubernetes', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(18, 'python', 'python', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(75, 'windows', 'Windows', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(69, 'unix', 'unix linux', false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(86, 'osb', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(101, 'proscons', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(96, 'setup', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(97, 'lib', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(104, 'tervezés', NULL, false);
INSERT INTO public.llabel (id, name, classifier_data, technical) VALUES(65, 'proglang', NULL, false);
